# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='/static/bliss-images/', max_length=200),
        ),
    ]
