# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bestseller',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.CharField(default='/static/bliss-files/', max_length=200),
        ),
    ]
